# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DGGRID
                                 A QGIS plugin
 This plugin creates DGGRID
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-27
        copyright            : (C) 2025 by DGGRID
        email                : DGGRID
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DGGRID class from file DGGRID.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dggrid import DGGRID
    return DGGRID(iface)
