# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DGGRIDDialog
                                 A QGIS plugin
 This plugin creates DGGRID
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2025 by DGGRID
        email                : DGGRID
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'dggrid_dialog_base.ui'))

FORM_CLASS2, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'option_window.ui'))


class DGGRIDDialog(QtWidgets.QDialog, QtWidgets.QApplication, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(DGGRIDDialog, self).__init__(parent)
        self.setupUi(self)


class OptionsWindow(QtWidgets.QDialog, QtWidgets.QApplication, FORM_CLASS2):
    def __init__(self, parent=None):
        """Constructor."""
        super(OptionsWindow, self).__init__(parent)
        self.setupUi(self)
