# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DGGRID
                                 A QGIS plugin
 This plugin creates DGGRID
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2025 by DGGRID
        email                : DGGRID
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QTableWidgetItem

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .dggrid_dialog import DGGRIDDialog, OptionsWindow

from .DrawRect import RectangleMapTool
from qgis.core import QgsVectorLayer, QgsProject, QgsVectorFileWriter, QgsCoordinateTransformContext, QgsMapLayer

from osgeo import ogr, osr
from pyproj import CRS, Transformer
from shapely.wkt import loads
from shapely.ops import transform
import os, requests, platform, stat, subprocess, uuid, sys
from collections import defaultdict
from glob import glob
import pandas as pd
from shapely.geometry import box
from shapely.geometry import Polygon

try:
    import h3
    from h3 import LatLngPoly
    h3_chc = 1
except:
    h3_chc = 0

class DGGRID:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'DGGRID_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&DGGRID Create')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('DGGRID', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/dggrid/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'This plugin creates DGGRID'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&DGGRID Create'),
                action)
            self.iface.removeToolBarIcon(action)

    def getTransformedGeometry(self, geom_wkt, srs_wkt, env=False):
        geom = loads(geom_wkt)
        
        from_crs = CRS.from_wkt(srs_wkt)
        to_crs = CRS.from_epsg(4326)
        
        transformer = Transformer.from_crs(from_crs, to_crs, always_xy=True)
        projected = transform(transformer.transform, geom)
        
        proj_geom = ogr.CreateGeometryFromWkt(projected.wkt)       
        
        if env:
            return proj_geom.GetEnvelope()
        else:
            return proj_geom

    def getCanvasExtent(self):
        canvas = QgsProject.instance()
        srs_wkt = canvas.crs().toWkt()
        ext = self.iface.mapCanvas().extent()
        
        minx, maxx, miny, maxy = self.getTransformedGeometry(ext.asWktPolygon(), srs_wkt, env=True)
            
        self.dlg.sb_extent_minx.setValue(minx)
        self.dlg.sb_extent_miny.setValue(miny)
        self.dlg.sb_extent_maxx.setValue(maxx)
        self.dlg.sb_extent_maxy.setValue(maxy)
     
    def getLayerExtent(self):
        layerName = self.dlg.cb_layers.currentText()
        layers = QgsProject.instance().mapLayersByName(layerName)
        if len(layers) > 0:
            srs_wkt = layers[0].crs().toWkt()        
            ext = layers[0].extent()
            
            minx, maxx, miny, maxy = self.getTransformedGeometry(ext.asWktPolygon(), srs_wkt, env=True)
                        
            self.dlg.sb_extent_minx.setValue(minx)
            self.dlg.sb_extent_miny.setValue(miny)
            self.dlg.sb_extent_maxx.setValue(maxx)
            self.dlg.sb_extent_maxy.setValue(maxy)
        

    def resetExtent(self):
        self.dlg.sb_extent_minx.setValue(0)
        self.dlg.sb_extent_miny.setValue(0)
        self.dlg.sb_extent_maxx.setValue(0)
        self.dlg.sb_extent_maxy.setValue(0)
    
    def getDrawnCoor(self, canvas):
        self.dlg.showMinimized()
        self.rect = RectangleMapTool(canvas, self.dlg)
        canvas.setMapTool(self.rect)

    def browseFolder(self):
        self.dlg.le_wdir.setText("")            
        output_dir = QFileDialog.getExistingDirectory(None, 'Open working directory', "", QFileDialog.ShowDirsOnly)
        self.dlg.le_wdir.setText(output_dir)

    def browseFolder2(self):
        self.dlg2.le_wdir.setText("")            
        output_dir = QFileDialog.getExistingDirectory(None, 'Open working directory', "", QFileDialog.ShowDirsOnly)
        self.dlg2.le_wdir.setText(output_dir)
    
    def browseFile(self):
        sender = self.dlg.sender()
        oname = sender.objectName()
        
        if oname == "pb_browsecellids":
            self.dlg.lw_cellids.clear()

            filePath, _filter = QFileDialog.getOpenFileName(self.dlg, "Select cell id file","", 'txt(*.txt *.TXT)')

            if os.path.isfile(filePath):
                with open(filePath) as f:
                    cell_id_txt = f.read()
            
                cell_id_list = set([i.strip() for i in cell_id_txt.split(",") if i.strip().isnumeric()])

                self.dlg.lw_cellids.addItems(sorted(cell_id_list))
    
    def getSelectedCellIds(self):
        try:
            layer = self.iface.activeLayer()
            features = layer.selectedFeatures()
            layer_name = layer.name()
            splitted = layer_name.split("_")
        except:
            features = []
            splitted = ""
        
        if len(splitted) >= 3:
            dggrid_type = splitted[1]
            res = splitted[2].removeprefix("r")
            
        try:
            self.dlg.cb_dggstype_2.setCurrentText(dggrid_type.upper())
        except:
            pass
        
        try:
            self.dlg.sb_resolution_2.setValue(int(res))
        except:
            pass
        
        self.dlg.lw_cellids.clear()
        for f in features:
            value = f.attribute("global_id")            
            self.dlg.lw_cellids.addItem(str(value))
            
    def typeChanged(self):
        sender = self.dlg.sender()
        oname = sender.objectName()
        
        if oname == "cb_dggstype":
            dgg_type = self.dlg.cb_dggstype.currentText()
            
            if dgg_type == "UBER H3":
                self.dlg.chb_metafile.setChecked(False)
                self.dlg.chb_centroid.setChecked(False)
                self.dlg.chb_wholeEarth.setChecked(False)
                
                self.dlg.chb_metafile.setEnabled(False)
                self.dlg.chb_centroid.setEnabled(False)
                self.dlg.chb_wholeEarth.setEnabled(False)
                
                self.dlg.sb_resolution.setMaximum(15)
                
            else:
                self.dlg.chb_metafile.setEnabled(True)
                self.dlg.chb_centroid.setEnabled(True)
                self.dlg.chb_wholeEarth.setEnabled(True)
                
                self.dlg.sb_resolution.setMaximum(35)
        
        elif oname == "cb_dggstype_2":
            dgg_type = self.dlg.cb_dggstype_2.currentText()
            self.dlg.lw_cellids.clear()
            
            if dgg_type == "UBER H3":
                self.dlg.chb_centroid_2.setChecked(False)
                self.dlg.chb_metafile_2.setChecked(False)
                
                self.dlg.chb_centroid_2.setEnabled(False)
                self.dlg.chb_metafile_2.setEnabled(False)
                
                self.dlg.sb_resolution_2.setMaximum(15)
                
                self.dlg.sb_cellid.setVisible(False)
                self.dlg.le_cellid.setVisible(True)
                
            else:
                self.dlg.chb_centroid_2.setEnabled(True)
                self.dlg.chb_metafile_2.setEnabled(True)
                
                self.dlg.sb_resolution_2.setMaximum(35)
                
                self.dlg.sb_cellid.setVisible(True)
                self.dlg.le_cellid.setVisible(False)
    
    def outFolderCheck(self):
        folder_path = self.dlg.le_wdir.text()
        
        if os.path.isdir(folder_path):
            self.dlg.lbl_wdir.setText("")
        else:
            self.dlg.lbl_wdir.setText('<html><head/><body><p><span style=" color:#ff0000;"> Invalid folder path! </span></p></body></html>')
        

    def addCellId(self):
        if self.dlg.cb_dggstype_2.currentText() == "UBER H3":
            value = self.dlg.le_cellid.text()
            self.dlg.lw_cellids.addItem(str(value))
            self.dlg.le_cellid.setText("")
            
            try:
                res = h3.get_resolution(value)
                self.dlg.sb_resolution_2.setValue(int(res))
            except:
                pass
            
        else:            
            value = int(self.dlg.sb_cellid.value())
            self.dlg.lw_cellids.addItem(str(value))
            self.dlg.sb_cellid.setValue(0)


    def clearCellId(self):
        self.dlg.lw_cellids.clear()
    
    def deleteCellId(self):
        if self.dlg.lw_cellids.count() > 0:
            selected_items = self.dlg.lw_cellids.selectedItems()
            for si in selected_items:
                selected_row = self.dlg.lw_cellids.row(si)
                self.dlg.lw_cellids.takeItem(selected_row)

    def download_exe(self):
        folder = os.path.dirname(__file__)
        
        uname = platform.uname()
        cpu = uname.machine.lower()
        opsystem = uname.system.lower()
        
        files = {
            'linux-aarch64': 'https://github.com/allixender/dggrid4py/releases/download/v0.3.2/dggrid-linux-aarch-gnu',
            'linux-x86_64': 'https://github.com/allixender/dggrid4py/releases/download/v0.3.2/dggrid-linux-x64',
            'darwin-arm64': 'https://github.com/allixender/dggrid4py/releases/download/v0.3.2/dggrid-macos-aarch',
            'windows-amd64': 'https://github.com/allixender/DGGRID/releases/download/v8.43b-1/dggrid-windows.exe'
        }

        url = files.get(f"{opsystem}-{cpu}", None)
        if url is None:
            raise ValueError(f"No portable executable available for {opsystem} {cpu}. Please use dggrid4py with a local DGGRID installation.")
                        
        filename = os.path.split(url)[-1]
        self.local_path = os.path.join(folder, filename)

        if not os.path.isfile(self.local_path):
            res = QMessageBox.question(None, "Message", """Executable file is not available. Do you want to download?""")
            if res == QMessageBox.Yes:
                try:
                    try:
                        response = requests.get(url, stream=True)
                    except:
                        response = requests.get(url, stream=True, verify=False)
                        
                    response.raise_for_status()
                    
                    with open(self.local_path, 'wb') as f:
                        for chunk in response.iter_content(chunk_size=8192):
                            f.write(chunk)

                    current_permissions = os.stat(self.local_path).st_mode
                    try:
                        os.chmod(self.local_path, current_permissions | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
                    except:
                        pass
                    
                    if os.path.isfile(self.local_path):
                        self.dlg.show()

                except:
                    pass            
            else:
                pass
        else:
            self.dlg.show()
    
    def createShapefile(self, clip_wkts, tmp_uuid, crs_wkt=None):
        outfile_name = f"region_{tmp_uuid}.shp"
        outfile_path = os.path.join(self.dlg.le_wdir.text(), outfile_name)
        
        driver = ogr.GetDriverByName("ESRI Shapefile")
        ds = driver.CreateDataSource(outfile_path)
        srs = osr.SpatialReference()
        if crs_wkt:
            srs.ImportFromWkt(crs_wkt)
        else:
            srs.ImportFromEPSG(4326)
        
        layer = ds.CreateLayer("region", srs, ogr.wkbPolygon)
        defn = layer.GetLayerDefn()
        
        for clip_wkt in clip_wkts:
            ogr_geom = ogr.CreateGeometryFromWkt(clip_wkt)
            
            feat = ogr.Feature(defn)
            feat.SetGeometry(ogr_geom)
        
            layer.CreateFeature(feat)
        
        ds = layer = defn = feat = None        
        
        return outfile_path
        
    
    def createPath1(self, shp_path, dtype):
        extention = {
            "SHP" : "shp",
            "GPKG" : "gpkg",
            "KML" : "kml",
            "GML" : "gml",
            "GEOJSON" : "geojson"
        }
        
        output_type = self.dlg.cb_dtype.currentText()
        
        outfile_name_ = self.dlg.le_outFileName.text()
        
        ext = extention[output_type]
        
        if outfile_name_:
            if dtype == "point":
                outfile_name = "point_" + outfile_name_.removesuffix(f".{ext}").replace(f".{ext}", f"_{ext}") + f".{ext}"
            else:
                outfile_name = "cell_" + outfile_name_.removesuffix(f".{ext}").replace(f".{ext}", f"_{ext}") + f".{ext}"
            
            suffix = 0
            while True:
                outfile_path = os.path.join(self.dlg.le_wdir.text(), outfile_name) if suffix==0 else os.path.join(self.dlg.le_wdir.text(), outfile_name.replace(f".{ext}", f"_{suffix}.{ext}"))    
                if not os.path.isfile(outfile_path):
                    break
                suffix += 1
            
        else:
            outfile_path = shp_path.replace("shp", ext)
        
        return outfile_path
    
    def createPath2(self, dtype, tmp_uuid):
        outfile_name_ = self.dlg.le_outFileName.text()
        working_folder_path = self.dlg.le_wdir.text()
        resolution = self.dlg.sb_resolution_2.value()
        
        if outfile_name_:
            if dtype == "nbr":
                outfile_name = "neighbors_" + outfile_name_.removesuffix(".txt").replace(".txt","_txt") + ".txt"
            else:
                outfile_name = "children_" + outfile_name_.removesuffix(".txt").replace(".txt","_txt") + ".txt"
            
            suffix = 0
            while True:
                outfile_path = os.path.join(self.dlg.le_wdir.text(), outfile_name) if suffix==0 else os.path.join(self.dlg.le_wdir.text(), outfile_name.replace(".gpkg", f"_{suffix}.gpkg"))    
                if not os.path.isfile(outfile_path):
                    break
                suffix += 1
            
        else:
            if dtype == "nbr":
                outfile_path = os.path.join(working_folder_path, f"nbr_seq_list_{self.dlg.cb_dggstype_2.currentText().lower()}_r{resolution}_{tmp_uuid}") + ".txt"
            else:
                outfile_path = os.path.join(working_folder_path, f"chd_seq_list_{self.dlg.cb_dggstype_2.currentText().lower()}_r{resolution}_{tmp_uuid}") + ".txt"
        
        return outfile_path
    
    
    def createGPKG(self, shp_path, dtype):
        
        output_type_dict = {
            "SHP" : "ESRI Shapefile",
            "GPKG" : "GPKG",
            "KML" : "KML",
            "GML" : "GML",
            "GEOJSON" : "GeoJSON"
        }
        
        output_type = self.dlg.cb_dtype.currentText()
        
        outfile_path = self.createPath1(shp_path, dtype)
        
        vec = ogr.Open(shp_path, 1)
        layer_shp = vec.GetLayer()
        features = list(layer_shp)
        
        vec = layer_shp = None
        
        for p in glob(os.path.join(shp_path.replace(".shp","") + "*")):
            if p.endswith("dbf") or p.endswith("shp") or p.endswith("shx"):
                os.remove(p)
        
        driver = ogr.GetDriverByName(output_type_dict[output_type])
        ds = driver.CreateDataSource(outfile_path)
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)
        
        if self.dlg.tabWidget.currentIndex() == 0:
            layer_name = f"dggrid_{self.dlg.cb_dggstype.currentText().lower()}_r{self.dlg.sb_resolution.value()}"
            
        elif self.dlg.tabWidget.currentIndex() == 1:
            layer_name = f"dggrid_{self.dlg.cb_dggstype_2.currentText().lower()}_r{self.dlg.sb_resolution_2.value()}"            
                
        if dtype == "polygon":
            layer = ds.CreateLayer(layer_name, srs, ogr.wkbPolygon)
        else:
            layer = ds.CreateLayer(layer_name, srs, ogr.wkbPoint)

        layer.CreateField(ogr.FieldDefn("global_id", ogr.OFTInteger64))
        defn = layer.GetLayerDefn()
        
        for en, feat_ in enumerate(features, 1):
            global_id = feat_.GetField("global_id")
            geom = feat_.GetGeometryRef()
            
            if output_type == "KML": geom.SwapXY()

            minx, maxx, miny, maxy = geom.GetEnvelope()
            diff_x = maxx - minx

            if (diff_x > 300):continue

            feat = ogr.Feature(defn)

            feat.SetGeometry(geom)
            feat.SetField("global_id", global_id)
            
            layer.CreateFeature(feat)
                  
        ds.FlushCache()
        
        ds = layer = defn = feat = None
        
        if self.dlg.cb_add_to_layer.isChecked():
            try:
                layer = QgsVectorLayer(outfile_path, layer_name, "ogr")
                QgsProject.instance().addMapLayer(layer)
            except:
                pass
        
    def createGPKG2(self, hexagons, out_path, out_type="polygon", child_res=None):
        
        output_type_dict = {
            "SHP" : "ESRI Shapefile",
            "GPKG" : "GPKG",
            "KML" : "KML",
            "GML" : "GML",
            "GEOJSON" : "GeoJSON"
        }
        
        tmp_uuid = str(uuid.uuid4())
        output_type = self.dlg.cb_dtype.currentText()
        
        outfile_name_ = self.dlg.le_outFileName.text()
        ext = output_type.lower()
        
        if outfile_name_:
            if out_type == "polygon":
                outfile_name = outfile_name_.removesuffix(f".{ext}").replace(f".{ext}", f"_{ext}") + f".{ext}"
            elif out_type == "neighbor":
                outfile_name = "nbr_" + outfile_name_.removesuffix(f".{ext}").replace(f".{ext}", f"_{ext}") + f".{ext}"
            elif out_type == "children":
                outfile_name = "chd_" + outfile_name_.removesuffix(f".{ext}").replace(f".{ext}", f"_{ext}") + f".{ext}"
        else:
            if out_type == "polygon":
                outfile_name = f"cell_h3_r{self.dlg.sb_resolution.value()}_{tmp_uuid}.{ext}"
            elif out_type == "neighbor":
                outfile_name = f"nbr_h3_r{self.dlg.sb_resolution.value()}_{tmp_uuid}.{ext}"
            elif out_type == "children":
                outfile_name = f"chd_h3_r{child_res}_{tmp_uuid}.{ext}"
        
        outfile_path = os.path.join(out_path, outfile_name)
        
        if os.path.isfile(outfile_path):
            outfile_path = os.path.join(out_path, outfile_name.replace(f".{ext}", f"_{tmp_uuid}.{ext}"))
        
        driver = ogr.GetDriverByName(output_type_dict[output_type])
        ds = driver.CreateDataSource(outfile_path)
        srs = osr.SpatialReference()
        srs.ImportFromEPSG(4326)
        
        if self.dlg.tabWidget.currentIndex() == 0:
            layer_name = f"dggrid_{self.dlg.cb_dggstype.currentText().lower()}_r{self.dlg.sb_resolution.value()}"
            
        elif self.dlg.tabWidget.currentIndex() == 1:
            if child_res:
                layer_name = f"dggrid_{self.dlg.cb_dggstype_2.currentText().lower()}_r{child_res}"
            else:
                layer_name = f"dggrid_{self.dlg.cb_dggstype_2.currentText().lower()}_r{self.dlg.sb_resolution_2.value()}"
                
        layer = ds.CreateLayer(layer_name, srs, ogr.wkbPolygon)

        layer.CreateField(ogr.FieldDefn("global_id", ogr.OFTString))
        defn = layer.GetLayerDefn()
        
        for global_id, geom_shapely in hexagons:
            
            geom_wkt = geom_shapely.wkt
            geom_ogr = ogr.CreateGeometryFromWkt(geom_wkt)
            
            if output_type == "KML": geom_ogr.SwapXY()
            
            feat = ogr.Feature(defn)

            feat.SetGeometry(geom_ogr)
            feat.SetField("global_id", global_id)
            
            layer.CreateFeature(feat)
                  
        ds.FlushCache()
        
        ds = layer = defn = feat = None
        
        if self.dlg.cb_add_to_layer.isChecked():
            try:
                layer = QgsVectorLayer(outfile_path, layer_name, "ogr")
                QgsProject.instance().addMapLayer(layer)
            except:
                pass
        
    def checkLayer(self):
        layerName = self.dlg.cb_layers.currentText()
        layers = QgsProject.instance().mapLayersByName(layerName)
        
        if len(layers) > 0:
            if (layers[0].type() == QgsMapLayer.VectorLayer) and (layers[0].geometryType() == 2):
                self.dlg.chb_use_features.setEnabled(True)
            else:
                self.dlg.chb_use_features.setEnabled(False)
            self.dlg.chb_use_features.setChecked(False)
    
    
    def createMetaDict(self, tmp_uuid, create_seqnum=True, create_region=True):
        working_folder_path = self.dlg.le_wdir.text()
        
        if self.dlg.tabWidget.currentIndex() == 0:
            
            minx = self.dlg.sb_extent_minx.value()
            miny = self.dlg.sb_extent_miny.value()
            maxx = self.dlg.sb_extent_maxx.value()
            maxy = self.dlg.sb_extent_maxy.value()
            
            
            if self.dlg.chb_wholeEarth.isChecked():
                clip_subset_type = "WHOLE_EARTH"
                clip_region_files = "NONE"
                
            elif self.dlg.chb_use_features.isChecked():
                if create_region:
                    layerName = self.dlg.cb_layers.currentText()
                    layers = QgsProject.instance().mapLayersByName(layerName)
                    if len(layers) > 0:
                        outfile_name = f"region_{tmp_uuid}.shp"
                        out_path = os.path.join(self.dlg.le_wdir.text(), outfile_name)
                        
                        crs_wkt = layers[0].crs().toWkt()
                        srs = osr.SpatialReference()
                        srs.ImportFromWkt(crs_wkt)
                        
                        features = layers[0].getFeatures()
                        
                        wkt_list = []

                        for feat in features:
                            wkt = feat.geometry().asWkt()
                            wkt_list.append(wkt)
                        
                        self.createShapefile(wkt_list, tmp_uuid, crs_wkt=crs_wkt)
                        
                        clip_region_files = out_path
                        clip_subset_type = "SHAPEFILE"
            
            else:
                clip_subset_type = "SHAPEFILE"
                clip_geom = box(minx, miny, maxx, maxy)
                if create_region:
                    clip_region_files = self.createShapefile([clip_geom.wkt], tmp_uuid)
                else:
                    outfile_name = f"region_{tmp_uuid}.shp"
                    clip_region_files = os.path.join(self.dlg.le_wdir.text(), outfile_name)
            
            dggrid_operation = "GENERATE_GRID"
            dggs_type = self.dlg.cb_dggstype.currentText()
            dggs_res_spec = self.dlg.sb_resolution.value()
            
            cell_output_type = "SHAPEFILE" if self.dlg.chb_polygon.isChecked() else "NONE"
            cell_output_file_name = os.path.join(working_folder_path, f"cell_{dggs_type.lower()}_r{dggs_res_spec}_{tmp_uuid}")
            
            point_output_type = "SHAPEFILE" if self.dlg.chb_centroid.isChecked() else "NONE"
            point_output_file_name = os.path.join(working_folder_path, f"point_{dggs_type.lower()}_r{dggs_res_spec}_{tmp_uuid}")
            
            meta_dict = {
                "dggrid_operation": dggrid_operation,
                "dggs_type": dggs_type,
                "dggs_res_spec": dggs_res_spec,
                "clip_subset_type": clip_subset_type,
                "clip_region_files": clip_region_files,
                "cell_output_type": cell_output_type,
                "cell_output_file_name": cell_output_file_name,
                "point_output_type": point_output_type,
                "point_output_file_name" : point_output_file_name,
                "longitude_wrap_mode" : "UNWRAP_EAST"
            }
            
            return meta_dict
        
        elif self.dlg.tabWidget.currentIndex() == 1:
            lw_cnt = self.dlg.lw_cellids.count()
            cell_id_list = set([self.dlg.lw_cellids.item(x).text() for x in range(lw_cnt)])
            
            seqnum_file_path = os.path.join(working_folder_path, "seqnums_" + tmp_uuid + ".txt")
            
            if create_seqnum:
                with open(seqnum_file_path, "w") as f:
                    f.write(",\n".join(cell_id_list)+"\n")
            
            dggrid_operation = "GENERATE_GRID"
            clip_subset_type = "SEQNUMS"
            dggs_type = self.dlg.cb_dggstype_2.currentText()
            dggs_res_spec = self.dlg.sb_resolution_2.value()
            
            clip_region_files = seqnum_file_path
            
            cell_output_type = "SHAPEFILE" if self.dlg.chb_polygon_2.isChecked() else "NONE"
            cell_output_file_name = os.path.join(working_folder_path, f"cell_{dggs_type.lower()}_{tmp_uuid}")
            
            point_output_type = "SHAPEFILE" if self.dlg.chb_centroid_2.isChecked() else "NONE"
            point_output_file_name = os.path.join(working_folder_path, f"point_{dggs_type.lower()}_{tmp_uuid}")
            
            neighbor_output_type = "TEXT"
            neighbor_output_file_name = os.path.join(working_folder_path, f"nbr_{dggs_type.lower()}_{tmp_uuid}")
            
            children_output_type = "TEXT"
            children_output_file_name = os.path.join(working_folder_path, f"chd_{dggs_type.lower()}_{tmp_uuid}")
            
            meta_dict = {
                "dggrid_operation": dggrid_operation,
                "dggs_type": dggs_type,
                "dggs_res_spec": dggs_res_spec,
                "clip_subset_type": clip_subset_type,
                "clip_region_files": clip_region_files,
                "cell_output_type": cell_output_type,
                "cell_output_file_name": cell_output_file_name,
                "point_output_type": point_output_type,
                "point_output_file_name" : point_output_file_name,
                "longitude_wrap_mode" : "UNWRAP_EAST"
            }
            
            if self.dlg.chb_neighbor_2.isChecked():
                meta_dict["neighbor_output_type"] = f"{neighbor_output_type}"
                meta_dict["neighbor_output_file_name"] = f"{neighbor_output_file_name}"
            
            if self.dlg.chb_children_2.isChecked():
                meta_dict["children_output_type"] = f"{children_output_type}"
                meta_dict["children_output_file_name"] = f"{children_output_file_name}"
            
            return meta_dict
            

    def createMetaFromDict(self, meta_dict):
        meta = ""
        for k,v in meta_dict.items():
            meta += f"{k} {v}\n"
        
        return meta
    
    def polygon_to_h3(self, geom, res):
        if geom.geom_type == "Polygon":
            exterior = [(lat, lng) for lng, lat in geom.exterior.coords]
            holes = [
                [(lat, lng) for lng, lat in ring.coords]
                for ring in geom.interiors
            ]
            poly = LatLngPoly(exterior, holes)
            return h3.polygon_to_cells(poly, res)

        elif geom.geom_type == "MultiPolygon":
            cells = set()
            for poly_geom in geom.geoms:
                exterior = [(lat, lng) for lng, lat in poly_geom.exterior.coords]
                holes = [
                    [(lat, lng) for lng, lat in ring.coords]
                    for ring in poly_geom.interiors
                ]
                poly = LatLngPoly(exterior, holes)
                cells.update(h3.polygon_to_cells(poly, res))
            return cells
        
    def get_neighbors(self, h3_id, k):
        neighbors = h3.grid_disk(h3_id, k)
        return list(neighbors)

    def get_children(self, h3_id, child_res):
        children = h3.cell_to_children(h3_id, child_res)
        return list(children)
    
    def run_uber_h3(self):
        if h3_chc == 0:
            QMessageBox.information(None, "ERROR", """H3 library is necessary for this grid type. Please install the library manually using OSGeo4W Shell and restart QGIS.\n (pip install h3)""")
        else:
            output_folder_path = self.dlg.le_wdir.text()
            resolution = self.dlg.sb_resolution.value()
            
            if not self.dlg.chb_use_features.isChecked():
                minx = self.dlg.sb_extent_minx.value()
                miny = self.dlg.sb_extent_miny.value()
                maxx = self.dlg.sb_extent_maxx.value()
                maxy = self.dlg.sb_extent_maxy.value()
                
                region_geom = box(minx, miny, maxx, maxy)
                
                all_cells = self.polygon_to_h3(region_geom, resolution)
            
            else:
                layerName = self.dlg.cb_layers.currentText()
                layers = QgsProject.instance().mapLayersByName(layerName)
                all_cells = set()
                geom_list = []
                
                if len(layers) > 0:                        
                    features = layers[0].getFeatures()
                    for feat in features:
                        wkt = feat.geometry().asWkt()
                        geom_list.append(loads(wkt))
                        
                    for geom in geom_list:
                        cells = self.polygon_to_h3(geom, resolution)
                        all_cells.update(cells)
            
            hexagons = []
            for cell in all_cells:
                boundary = h3.cell_to_boundary(cell)
                hexagon = Polygon([(lng, lat) for lat, lng in boundary])
                hexagons.append([cell, hexagon])
            
            self.createGPKG2(hexagons, output_folder_path)
            

    def execute(self):        
        working_folder_path = self.dlg.le_wdir.text()
        
        if not os.path.isdir(self.dlg.le_wdir.text()):
            QMessageBox.critical(None, "ERROR", """Invalid working directory!""")
            return
        
        if self.dlg.tabWidget.currentIndex() == 0:
            dgg_type = self.dlg.cb_dggstype.currentText() + "_t1"
            
            if not (self.dlg.chb_polygon.isChecked() or self.dlg.chb_centroid.isChecked() or self.dlg.chb_metafile.isChecked()):
                QMessageBox.critical(None, "ERROR", """Output Type is not selected!""")
                return
        
        elif self.dlg.tabWidget.currentIndex() == 1:
            dgg_type = self.dlg.cb_dggstype_2.currentText() + "_t2"
            
            if not any([self.dlg.chb_polygon_2.isChecked(), self.dlg.chb_centroid_2.isChecked(),
                        self.dlg.chb_neighbor_2.isChecked(), self.dlg.chb_children_2.isChecked(), self.dlg.chb_metafile_2.isChecked()]):
                QMessageBox.critical(None, "ERROR", """Output Type is not selected!""")
                return                

        self.dlg.btn_execute.setText("GENERATING...")
        self.dlg.setEnabled(False)
        self.dlg.processEvents()

        exe_path = self.local_path
        
        
        if dgg_type == "UBER H3_t1":
            self.run_uber_h3()

        if dgg_type == "UBER H3_t2":
            output_folder_path = self.dlg.le_wdir.text()
            
            lw_cnt = self.dlg.lw_cellids.count()
            cell_id_list = set([self.dlg.lw_cellids.item(x).text() for x in range(lw_cnt)])
            
            if self.dlg.chb_polygon_2.isChecked():
                all_cells = set()
                
                for cell_id in cell_id_list:
                    cells = self.get_neighbors(cell_id, 0)
                    all_cells.update(cells)
        
                hexagons = []
                for cell in all_cells:
                    boundary = h3.cell_to_boundary(cell)
                    hexagon = Polygon([(lng, lat) for lat, lng in boundary])
                    hexagons.append([cell, hexagon])
                
                self.createGPKG2(hexagons, output_folder_path, out_type="polygon")
                
            
            if self.dlg.chb_neighbor_2.isChecked():
                all_cells = set()
                
                for cell_id in cell_id_list:
                    cells = self.get_neighbors(cell_id, 1)
                    all_cells.update(cells)
        
                hexagons = []
                for cell in all_cells:
                    boundary = h3.cell_to_boundary(cell)
                    hexagon = Polygon([(lng, lat) for lat, lng in boundary])
                    hexagons.append([cell, hexagon])
                
                self.createGPKG2(hexagons, output_folder_path, out_type="neighbor")
            
            if self.dlg.chb_children_2.isChecked():
                all_cells = set()
                                
                for cell_id in cell_id_list:
                    child_res = min(h3.get_resolution(cell_id) + 1, 15)
                    cells = self.get_children(cell_id, child_res)
                    all_cells.update(cells)                    
        
                hexagons = []
                for cell in all_cells:
                    boundary = h3.cell_to_boundary(cell)
                    hexagon = Polygon([(lng, lat) for lat, lng in boundary])
                    hexagons.append([cell, hexagon])
                
                self.createGPKG2(hexagons, output_folder_path, out_type="children", child_res=child_res)
        
        else:
            try:
                tmp_uuid = str(uuid.uuid4())
                meta_dict = self.createMetaDict(tmp_uuid)
                meta = self.createMetaFromDict(meta_dict)
                
                cell_output_file_name = meta_dict["cell_output_file_name"]
                point_output_file_name = meta_dict["point_output_file_name"]
                
                meta_file_path = os.path.join(working_folder_path, f"metafile_{tmp_uuid}")
                
                with open(meta_file_path, "w") as f:
                    f.write(meta)
    
                cmd = [exe_path, meta_file_path]
    
                subprocess.call(cmd)
                
                if self.dlg.tabWidget.currentIndex() == 0:
                
                    if self.dlg.chb_polygon.isChecked():
                        try:
                            os.remove(cell_output_file_name + ".prj")
                            self.createGPKG(cell_output_file_name + ".shp", "polygon")
                        except:
                            pass
                        
                    if self.dlg.chb_centroid.isChecked():
                        try:
                            os.remove(point_output_file_name + ".prj")
                            self.createGPKG(point_output_file_name + ".shp", "point")
                        except:
                            pass
                    
                    for s in glob(os.path.join(working_folder_path, "*" + tmp_uuid + ".*")):
                        if not self.dlg.chb_metafile.isChecked():
                            if ("region_" in s):
                                os.remove(s)
                
                    if not self.dlg.chb_metafile.isChecked():
                        os.remove(meta_file_path)                
    
                if self.dlg.tabWidget.currentIndex() == 1:
                    if meta_dict.get("neighbor_output_file_name"):
                        neighbor_output_file_name = meta_dict["neighbor_output_file_name"]
                    
                    if meta_dict.get("children_output_file_name"):
                        children_output_file_name = meta_dict["children_output_file_name"]
                    
                    if self.dlg.chb_neighbor_2.isChecked():
                        nbr_path = neighbor_output_file_name + ".nbr"
                        nbr_out_path = self.createPath2(dtype="nbr", tmp_uuid=tmp_uuid)
                        
                        if os.path.isfile(nbr_path):
                            nbr_txt = ""
                            with open(nbr_path) as f:
                                nbr_list = f.readlines()
                                for nl_ in nbr_list:
                                    nl = nl_.strip().split()
                                    nbr_txt += f"# {nl[0]},\n"
                                    nbr_txt += f"{','.join(nl[1:])},\n"
                            
                            with open(nbr_out_path, "w") as f:
                                f.write(nbr_txt)
                        
                        os.remove(nbr_path)
                    
                    if self.dlg.chb_children_2.isChecked():
                        chd_path = children_output_file_name + ".chd"
                        chd_out_path = self.createPath2(dtype="chd", tmp_uuid=tmp_uuid)
                        
                        if os.path.isfile(chd_path):
                            chd_txt = ""
                            with open(chd_path) as f:
                                chd_list = f.readlines()
                                for cl_ in chd_list:
                                    cl = cl_.strip().split()
                                    chd_txt += f"# {cl[0]},\n"
                                    chd_txt += f"{','.join(cl[1:])},\n"
                            
                            with open(chd_out_path, "w") as f:
                                f.write(chd_txt)
                        
                        os.remove(chd_path)
                    
                    if self.dlg.chb_polygon_2.isChecked():
                        try:
                            os.remove(cell_output_file_name + ".prj")
                            self.createGPKG(cell_output_file_name + ".shp", "polygon")
                        except:
                            pass
                        
                    if self.dlg.chb_centroid_2.isChecked():
                        try:
                            os.remove(point_output_file_name + ".prj")
                            self.createGPKG(point_output_file_name + ".shp", "point")
                        except:
                            pass
                    
                    for s in glob(os.path.join(working_folder_path, "*" + tmp_uuid + ".*")):
                        if not self.dlg.chb_metafile_2.isChecked():
                            if ("seqnums_" in s):
                                os.remove(s)
                    
                    if not self.dlg.chb_metafile_2.isChecked():
                        os.remove(meta_file_path)
            
            except Exception as ex:
                print(ex)
                exc_type, exc_obj, exc_tb = sys.exc_info()
                fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                print(exc_type, fname, exc_tb.tb_lineno)
        
        self.dlg.btn_execute.setText("GENERATE GRIDS")
        self.dlg.setEnabled(True)
        self.dlg.processEvents()

        self.dlg.show()


    def optionsScreen(self):
        self.tmp_uuid2 = str(uuid.uuid4())
        
        table = self.dlg2.table_options
        row_cnt = table.rowCount()
        
        for r in range(row_cnt):
            table.removeRow(0)
        
        item_list = [i for i in self.createMetaDict(self.tmp_uuid2, create_seqnum=False, create_region=False).items()]
        
        for e, (k,v) in enumerate(item_list):
            table.insertRow(e)
            
            table.setItem(e , 0, QTableWidgetItem(k))
            table.setItem(e , 1, QTableWidgetItem(str(v)))
            
        self.dlg2.show()
        
    
    def loadFromGui(self):
        table = self.dlg2.table_options
        row_cnt = table.rowCount()
        
        for r in range(row_cnt):
            table.removeRow(0)
        
        item_list = [i for i in self.createMetaDict(self.tmp_uuid2, create_seqnum=False, create_region=False).items()]
        
        for e, (k,v) in enumerate(item_list):
            table.insertRow(e)
            
            table.setItem(e , 0, QTableWidgetItem(k))
            table.setItem(e , 1, QTableWidgetItem(str(v)))
        
    
    def optionsTable(self):
        sender = self.dlg2.sender()
        oname = sender.objectName()
        
        table = self.dlg2.table_options
        
        if oname == "pb_addline":
            row_cnt = table.rowCount()
            table.insertRow(row_cnt)
        
        elif oname == "pb_removeline":
            current_row = table.currentRow()
            
            if current_row >= 0:
                table.removeRow(current_row)
                
        elif oname == "pb_cleartable":
            row_cnt = table.rowCount()
            
            for r in range(row_cnt):
                table.removeRow(0)
        
        elif oname == "pb_run":
            meta_dict = {}
            row_cnt = table.rowCount()
            
            for row in range(row_cnt):
                k = table.item(row, 0).text()
                v = table.item(row, 1).text()
                
                meta_dict[k] = v
                
            meta = self.createMetaFromDict(meta_dict)
            
            self.dlg.btn_execute.setText("GENERATING...")
            self.dlg.setEnabled(False)
            self.dlg.processEvents()
            
            meta_folder_path = self.dlg2.le_wdir.text()
            meta_file_name = f"metafile_{self.tmp_uuid2}"
            
            if not os.path.isdir(meta_folder_path):
                QMessageBox.critical(None, "ERROR", """Invalid working directory!""")
                return
            
            meta_file_path = os.path.join(meta_folder_path, meta_file_name)
            
            with open(meta_file_path, "w") as f:
                f.write(meta)
                
            exe_path = self.local_path
            cmd = [exe_path, meta_file_path]

            subprocess.call(cmd)
            
            
            self.dlg.btn_execute.setText("GENERATE")
            self.dlg.setEnabled(True)
            self.dlg.processEvents()
            
    
    def wholeEarth(self):
        if self.dlg.chb_wholeEarth.isChecked():
            for chd in self.dlg.groupBox.children():
                if not chd.objectName() == "chb_wholeEarth":
                    chd.setEnabled(False)
        else:
            for chd in self.dlg.groupBox.children():
                chd.setEnabled(True)
    
    def onCloseEvent(self, event):
        self.dlg2.close()

    def run(self):
        if self.first_start == True:
            self.dlg = DGGRIDDialog()
            self.dlg2 = OptionsWindow()
            
            self.dlg.closeEvent = self.onCloseEvent

            self.download_exe()
            
            self.dlg.setWindowIcon(QIcon(':/plugins/dggrid/icon.png'))
            self.dlg.lbl_wdir.setText('<html><head/><body><p><span style=" color:#ff0000;"> Invalid folder path! </span></p></body></html>')

            layers = [v.name() for v in QgsProject.instance().mapLayers().values()]
            self.dlg.cb_layers.clear()
            self.dlg.cb_layers.addItems(layers)
            self.checkLayer()
            
            self.dlg.cb_dggstype.insertSeparator(15)
            self.dlg.cb_dggstype_2.insertSeparator(15)
            self.dlg.le_cellid.setVisible(False)
            
            self.dlg.btn_canvasExtent.clicked.connect(self.getCanvasExtent)
            self.dlg.btn_layerextent.clicked.connect(self.getLayerExtent)
            self.dlg.tbtn_draw.clicked.connect(lambda x:self.getDrawnCoor(self.iface.mapCanvas()))
            
            self.dlg.cb_dggstype.currentTextChanged.connect(self.typeChanged)
            self.dlg.cb_dggstype_2.currentTextChanged.connect(self.typeChanged)

            self.dlg.btn_reset.clicked.connect(self.resetExtent)
            self.dlg.btn_browse.clicked.connect(self.browseFolder)
            self.dlg2.btn_browse.clicked.connect(self.browseFolder2)

            self.dlg.btn_execute.clicked.connect(self.execute)

            self.dlg.pb_addcellid.clicked.connect(self.addCellId)
            self.dlg.pb_clearcellids.clicked.connect(self.clearCellId)
            self.dlg.pb_deletecellid.clicked.connect(self.deleteCellId)
            self.dlg.pb_browsecellids.clicked.connect(self.browseFile)
            self.dlg.pb_getselected_2.clicked.connect(self.getSelectedCellIds)
            self.dlg.chb_wholeEarth.stateChanged.connect(self.wholeEarth)
            self.dlg.le_wdir.textChanged[str].connect(self.outFolderCheck)
            
            self.dlg.cb_layers.currentTextChanged.connect(self.checkLayer)
            
            self.dlg.pb_options.clicked.connect(self.optionsScreen)
            self.dlg2.pb_loadFromGui.clicked.connect(self.loadFromGui)
            
            self.dlg2.table_options.setColumnWidth(0, 135)
            self.dlg2.table_options.setColumnWidth(1, 350)
            
            self.dlg2.pb_addline.clicked.connect(self.optionsTable)
            self.dlg2.pb_removeline.clicked.connect(self.optionsTable)
            self.dlg2.pb_cleartable.clicked.connect(self.optionsTable)
            self.dlg2.pb_run.clicked.connect(self.optionsTable)
            
            
            